version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: kh-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kh-network

  vectordb:
    image: qdrant/qdrant:latest
    container_name: kh-vectordb
    restart: unless-stopped
    ports:
      - '9000:6333'
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:6333/health',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kh-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kh-app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      vectordb:
        condition: service_started
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:${PORT}/doc || exit 1',
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - kh-network

  adminer:
    image: adminer
    container_name: kh-adminer
    restart: always
    profiles:
      - debug
    ports:
      - '8080:8080'
    networks:
      - kh-network

networks:
  kh-network:
    driver: bridge

volumes:
  postgres_data:
  qdrant_data:
